dispatcher: mettle dispatcher
logcollector: mettle logcollector
migrate: mettle migrate_and_sleep
publisher: mettle publisher
timer: mettle timer
web: mettle web
service_pizza: python scripts/pizza_service.py
service_sun: python scripts/sun_service.py
datastub: python scripts/datastub.py
