web: mettle web
timer: mettle timer
dispatcher: mettle dispatcher
publisher: mettle publisher
logcollector: mettle logcollector
migrate: mettle migrate_and_sleep
service_pizza: python scripts/pizza_service.py
service_sun: python scripts/sun_service.py
datastub: python scripts/datastub.py
